server:
  port: '8080'

spring:
  datasource:
    url: 'jdbc:mysql://${DB_HOST}:${DB_PORT}/smarthome'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      ddl-auto: update