allow:
  ip: '*.*.*.*'

server:
  port: '8080'

spring:
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/smarthome'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
